"""empty message

Revision ID: 1e71e3b2ec44
Revises: 49d595a86789
Create Date: 2024-06-13 11:26:29.362480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e71e3b2ec44'
down_revision = '49d595a86789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img1', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('url_img1')

    # ### end Alembic commands ###
